---
enable-beta-ecosystems: true  # Enables Helm dependency checking

version: 2
updates:
  - package-ecosystem: helm
    directory: /charts/alloy-helm-chart
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    labels:
      - dependencies
      - helm

  - package-ecosystem: docker
    directory: /operator
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    labels:
      - dependencies
      - github-actions
