---
yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint"

extends: default

ignore:
  - charts/**/templates
  - charts/alloy-helm-chart/charts/**/*
  - charts/alloy-operator/alloy-values.yaml
  - charts/alloy-operator/charts/**/crds
  - tests/integration/**/kubeconfig.yaml
rules:
  line-length:
    max: 200
    level: warning
