---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: operator/helm-charts
    contents:
      - path: alloy
        helmChart:
          name: alloy
          version: 0.12.5
          repository:
            url: https://grafana.github.io/helm-charts
        excludePaths:
          - Chart.lock
          - charts/**/*
  - path: charts/alloy-operator/charts/pod-logs-crd/crds
    contents:
      - path: .
        helmChart:
          name: alloy
          version: 0.12.5
          repository:
            url: https://grafana.github.io/helm-charts
        includePaths:
          - charts/crds/crds/monitoring.grafana.com_podlogs.yaml
        newRootPath: charts/crds/crds