{{- if and (or .Values.crds.deployAlloyCRD .Values.crds.deployPodLogsCRD) .Values.crds.upgradeJob.enabled }}
{{- if .Values.crds.upgradeJob.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.crds.upgradeJob.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ .Values.crds.upgradeJob.serviceAccount.name | default (include "alloy-operator.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.crds.upgradeJob.serviceAccount.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- with .Values.crds.upgradeJob.serviceAccount.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "alloy-operator.fullname" . }}-upgrade
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - create
      - patch
      - update
      - get
      - list
    resourceNames:
{{- if .Values.crds.deployAlloyCRD }}
      - alloys.collectors.grafana.com
{{- end }}
{{- if .Values.crds.deployPodLogsCRD }}
      - podlogs.monitoring.grafana.com
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "alloy-operator.fullname" . }}-upgrade
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
subjects:
  - kind: ServiceAccount
    name: {{ .Values.crds.upgradeJob.serviceAccount.name | default (include "alloy-operator.fullname" .) }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "alloy-operator.fullname" . }}-upgrade
  apiGroup: rbac.authorization.k8s.io
{{- end }}
