---
{{- if and ((.Values.global).imageRegistry) (((.Values.global).image).registry) }}
  {{- $msg := list "" "global.imageRegistry is deprecated and cannot be set at the same time as global.image.registry." }}
  {{- $msg = append $msg "Please set only global.image.registry:" }}
  {{- $msg = append $msg "alloy-operator:" }}
  {{- $msg = append $msg "  global:" }}
  {{- $msg = append $msg "    image:" }}
  {{- $msg = append $msg "      registry: my-registry.example.com" }}
  {{- fail (join "\n" $msg) }}
{{- end }}
{{- if and ((.Values.global).imagePullPolicy) (((.Values.global).image).pullPolicy) }}
  {{- $msg := list "" "global.imagePullPolicy is deprecated and cannot be set at the same time as global.image.pullPolicy." }}
  {{- $msg = append $msg "Please set only global.image.pullPolicy:" }}
  {{- $msg = append $msg "alloy-operator:" }}
  {{- $msg = append $msg "  global:" }}
  {{- $msg = append $msg "    image:" }}
  {{- $msg = append $msg "      pullPolicy: Always" }}
  {{- fail (join "\n" $msg) }}
{{- end }}
