---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{- include "alloy-operator.fullname" . | nindent 4 }}-leader-election-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alloy-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{- include "alloy-operator.fullname" . | nindent 4 }}-alloy-editor-role
  labels:
    {{- include "alloy-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - collectors.grafana.com
    resources:
      - alloys
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - collectors.grafana.com
    resources:
      - alloys/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{- include "alloy-operator.fullname" . | nindent 4 }}-alloy-viewer-role
  labels:
    {{- include "alloy-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - collectors.grafana.com
    resources:
      - alloys
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - collectors.grafana.com
    resources:
      - alloys/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{- include "alloy-operator.fullname" . | nindent 4 }}-role
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - collectors.grafana.com
    resources:
      - alloys
      - alloys/status
      - alloys/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - configmaps
      - serviceaccounts
      - services
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{- include "alloy-operator.fullname" . | nindent 4 }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alloy-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{- include "alloy-operator.fullname" . | nindent 4 }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "alloy-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{- include "alloy-operator.fullname" . | nindent 4 }}-rolebinding
  labels:
    {{- include "alloy-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{- include "alloy-operator.fullname" . | nindent 4 }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "alloy-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
