apiVersion: v2
appVersion: v1.12.0
dependencies: []
description: Grafana Alloy
icon: https://raw.githubusercontent.com/grafana/alloy/main/docs/sources/assets/alloy_icon_orange.svg
name: alloy
type: application
version: 1.5.0
