resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: ghcr.io/grafana/alloy-operator
  newTag: 1.8.0@sha256:831b13a2909e613e67181159db0ca46e76416e5066d046a14185c43f5b6ba9b4
