---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-parent-chart.fullname" . }}
  labels:
    {{- include "sample-parent-chart.labels" . | nindent 4 }}
data:
  VERSION: {{ .Chart.Version | quote }}
