---
name: Release Alloy Operator Helm chart
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:
  release:
    uses: grafana/helm-charts/.github/workflows/update-helm-repo.yaml@83f3d40874194df669168e4109da3b7e4e8c5089
    permissions:
      contents: write
      id-token: write
      packages: write
    with:
      charts_dir: charts
      cr_configfile: cr.yaml
      ct_configfile: charts/alloy-operator/ct.yaml
    secrets:
      vault_repo_secret_name: github-app
